2025-09-13 20:23:58,378 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError('Could not parse the remainder: \'Reset\' from \'""Reset\''), <traceback object at 0x0000014AB82F7B00>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\templatetags\i18n.py", line 403, in do_translate
    message_string = parser.compile_filter(bits[1])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: 'Reset' from '""Reset'
2025-09-13 20:23:58,381 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/?title__icontains=&username=&date_after= HTTP/1.1" 500 278530
None
2025-09-13 21:09:05,029 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'TypeError'>, TypeError("pgettext() missing 1 required positional argument: 'message'"), <traceback object at 0x00000218A956E880>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\hashable.py", line 20, in make_hashable
    hash(value)
TypeError: unhashable type: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\hashable.py", line 20, in make_hashable
    hash(value)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\functional.py", line 152, in __hash__
    return hash(self.__cast())
                ^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: pgettext() missing 1 required positional argument: 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\hashable.py", line 20, in make_hashable
    hash(value)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\functional.py", line 152, in __hash__
    return hash(self.__cast())
                ^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: pgettext() missing 1 required positional argument: 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 925, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\base.py", line 1295, in _get_FIELD_display
    choices_dict = dict(make_hashable(field.flatchoices))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\hashable.py", line 23, in make_hashable
    return tuple(map(make_hashable, value))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\hashable.py", line 23, in make_hashable
    return tuple(map(make_hashable, value))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\hashable.py", line 23, in make_hashable
    return tuple(map(make_hashable, value))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: pgettext() missing 1 required positional argument: 'message'
2025-09-13 21:09:05,032 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 331201
None
2025-09-13 21:43:09,571 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/create/
(<class 'NameError'>, NameError("name 'cache' is not defined"), <traceback object at 0x000001DF1C668540>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 106, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\models.py", line 88, in save
    cache.delete(f'product-{self.pk}')
    ^^^^^
NameError: name 'cache' is not defined
2025-09-13 21:43:09,574 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "POST /news/create/ HTTP/1.1" 500 108255
None
2025-09-13 21:43:54,033 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/create/
(<class 'TypeError'>, TypeError("post_created() missing 1 required positional argument: 'created'"), <traceback object at 0x000001D1457A7340>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 106, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\forms\models.py", line 555, in save
    self._save_m2m()
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\forms\models.py", line 536, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related.py", line 2034, in save_form_data
    getattr(instance, self.attname).set(data)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1352, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1253, in add
    self._add_items(
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1538, in _add_items
    signals.m2m_changed.send(
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: post_created() missing 1 required positional argument: 'created'
2025-09-13 21:43:54,035 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "POST /news/create/ HTTP/1.1" 500 134593
None
2025-09-13 21:54:02,955 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/create/
(<class 'TypeError'>, TypeError("post_created() missing 1 required positional argument: 'created'"), <traceback object at 0x000001E9206D1980>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 106, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\forms\models.py", line 555, in save
    self._save_m2m()
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\forms\models.py", line 536, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related.py", line 2034, in save_form_data
    getattr(instance, self.attname).set(data)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1352, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1253, in add
    self._add_items(
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1538, in _add_items
    signals.m2m_changed.send(
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: post_created() missing 1 required positional argument: 'created'
2025-09-13 21:54:02,958 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "POST /news/create/ HTTP/1.1" 500 134465
None
2025-09-13 21:56:19,645 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/create/
(<class 'TypeError'>, TypeError("post_created() missing 1 required positional argument: 'created'"), <traceback object at 0x000001CC867F9F80>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 106, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\forms\models.py", line 555, in save
    self._save_m2m()
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\forms\models.py", line 536, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related.py", line 2034, in save_form_data
    getattr(instance, self.attname).set(data)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1352, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1253, in add
    self._add_items(
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1538, in _add_items
    signals.m2m_changed.send(
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: post_created() missing 1 required positional argument: 'created'
2025-09-13 21:56:19,648 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "POST /news/create/ HTTP/1.1" 500 134541
None
2025-09-14 18:22:45,886 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'NameError'>, NameError("name 'get_language' is not defined"), <traceback object at 0x000001951DC8AF80>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 29, in get_queryset
    current_language = get_language()
                       ^^^^^^^^^^^^
NameError: name 'get_language' is not defined
2025-09-14 18:22:45,887 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 96638
None
2025-09-14 18:22:46,541 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'NameError'>, NameError("name 'get_language' is not defined"), <traceback object at 0x000001951DC10880>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 29, in get_queryset
    current_language = get_language()
                       ^^^^^^^^^^^^
NameError: name 'get_language' is not defined
2025-09-14 18:22:46,542 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 96638
None
2025-09-14 18:24:03,735 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'NameError'>, NameError("name 'activate' is not defined"), <traceback object at 0x0000017D8A4576C0>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 32, in get_queryset
    activate(current_language)
    ^^^^^^^^
NameError: name 'activate' is not defined
2025-09-14 18:24:03,736 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 96774
None
2025-09-14 18:24:04,590 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'NameError'>, NameError("name 'activate' is not defined"), <traceback object at 0x0000017D8A452500>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 32, in get_queryset
    activate(current_language)
    ^^^^^^^^
NameError: name 'activate' is not defined
2025-09-14 18:24:04,590 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 96774
None
2025-09-14 18:30:05,226 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid filter: 'add_class'"), <traceback object at 0x00000249BE0B7EC0>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
2025-09-14 18:30:05,229 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 312184
None
2025-09-14 18:30:05,995 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid filter: 'add_class'"), <traceback object at 0x00000249BDE920C0>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
2025-09-14 18:30:05,997 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 312184
None
2025-09-14 18:42:01,747 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/
(<class 'NameError'>, NameError("name 'HttpResponse' is not defined"), <traceback object at 0x000002595C52A000>)
Traceback (most recent call last):
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ильназ\PycharmProjects\News_project\NewsPaper\news\views.py", line 48, in get
    return HttpResponse(render(request, self.template_name, context))
           ^^^^^^^^^^^^
NameError: name 'HttpResponse' is not defined
2025-09-14 18:42:01,748 ERROR C:\Users\Ильназ\PycharmProjects\News_project\.venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/ HTTP/1.1" 500 93664
None
